### ISSUE TITLE
einsum??

### ISSUE THREAD

**Issue by sstary** [jeya-maria-jose/Medical-Transformer#12]
how could I solve this problm?

RuntimeError: size of dimension does not match previous size, operand 1, dim 1

**Comment by sstary** [comment]
You have to resize image by hand

**Comment by JackHeroFly** [comment]
> how could I solve this problm?
> 
> RuntimeError: size of dimension does not match previous size, operand 1, dim 1

Hello,do you solve the issue "RuntimeError: size of dimension does not match previous size, operand 1, dim 1"?  I encounter this error too.
