### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by jm-R152** [jeya-maria-jose/Medical-Transformer#13]
Thank you for your excellent code. Could you tell me what is the image size when you used to train your network. If I want to use my own image, for example the image with size 512 x 512, what parameters should I modify? Since when I try to re-implement your project, I encountered some dimensions issues, like 

RuntimeError: einsum() operands do not broadcast with remapped shapes [original->remapped]: [1024, 8, 1, 512]->[1024, 8, 512, 1, 1] [1, 128, 128]->[1, 1, 128, 128, 1]

Could you give me some hints?

**Comment by jeya-maria-jose** [comment]
Hi, 

The image size used in most experiments is 128 x 128. However, you can use the argument imgsize to change the network work on a different resolution image. So, please make --imgsize as 512. If you want to have more control on the code, please modify the kernel_size argument in [_make_layer(](https://github.com/jeya-maria-jose/Medical-Transformer/blob/3e0e54b95dfbb91e30b8e5def16fa949712799f6/lib/models/axialnet.py#L592))

**Comment by ssli23** [comment]
> Thank you for your excellent code. Could you tell me what is the image size when you used to train your network. If I want to use my own image, for example the image with size 512 x 512, what parameters should I modify? Since when I try to re-implement your project, I encountered some dimensions issues, like
> 
> RuntimeError: einsum() operands do not broadcast with remapped shapes [original->remapped]: [1024, 8, 1, 512]->[1024, 8, 512, 1, 1] [1, 128, 128]->[1, 1, 128, 128, 1]
> 
> Could you give me some hints?

I have the same problem, have you solved this problem? looking forward to your reply 

have

**Comment by aliwaqas333** [comment]
The kernel sizes are fixed, so you have to make your own changes in code to run on different size image.
