### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by hritam-98** [jeya-maria-jose/Medical-Transformer#14]
While using the colab version of the code, the code works fine up to training. But while executing the following shell:
`command2="python Medical-Transformer/test.py \
--loaddirec \"{}\" \
--val_dataset \"{}\" \
--direc '{}' \
--batch_size 1 \
--modelname \"MedT\" \
--imgsize 128 \
--gray \"no\"".format('/content/train results/390/MedT.pth',test_DIR,test_rese_DIR)
!{command2}`

the following error occurs:

Traceback (most recent call last):
  File "Medical-Transformer/test.py", line 82, in <module>
    train_dataset = ImageToImage2D(args.train_dataset, tf_val)
  File "/content/Medical-Transformer/utils.py", line 130, in __init__
    self.input_path = os.path.join(dataset_path, '/img')
  File "/usr/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Please help :)

**Comment by NguyenDangBinh** [comment]
dear @hritam-98,
Are you fix it?
I still got the same.
