### ISSUE TITLE
Larger training image input size results "cuda out of memory" error

### ISSUE THREAD

**Issue by weiaicunzai** [jeya-maria-jose/Medical-Transformer#17]
Hi, sorry to bother you, really appreciate your work. I recently trained the ``axialunet`` with  input size 473, and it gives me a cuda out of memory error, I also noticed that you seems to comment out the ``decoder1``, ``decoder2``, ``decoder3`` code in ``medt_net``, could you please tell me why? Is it because the memory consumption problem?Thanks in advance.

**Comment by jeya-maria-jose** [comment]
Hi, Thanks for your interest in the work. I think you can try reducing the number for channels to fit the memory. You can control that by changing values `s` and `layers` from the [function definition](https://github.com/jeya-maria-jose/Medical-Transformer/blob/3e0e54b95dfbb91e30b8e5def16fa949712799f6/lib/models/axialnet.py#L714).

Regarding the `medt_net` part, I had commented that out mainly for reducing the time taken for training.

**Comment by weiaicunzai** [comment]
> Hi, Thanks for your interest in the work. I think you can try reducing the number for channels to fit the memory. You can control that by changing values `s` and `layers` from the [function definition](https://github.com/jeya-maria-jose/Medical-Transformer/blob/3e0e54b95dfbb91e30b8e5def16fa949712799f6/lib/models/axialnet.py#L714).
> 
> Regarding the `medt_net` part, I had commented that out mainly for reducing the time taken for training.

Thanks for your replay, is there any suggested smaller ``s`` value? I've tried 0.0625, 0.1. 0.05, a little hard to find the correct ``s`` value. Thank you.

**Comment by NguyenDangBinh** [comment]
> > Hi, Thanks for your interest in the work. I think you can try reducing the number for channels to fit the memory. You can control that by changing values `s` and `layers` from the [function definition](https://github.com/jeya-maria-jose/Medical-Transformer/blob/3e0e54b95dfbb91e30b8e5def16fa949712799f6/lib/models/axialnet.py#L714).
> > Regarding the `medt_net` part, I had commented that out mainly for reducing the time taken for training.
> 
> Thanks for your replay, is there any suggested smaller `s` value? I've tried 0.0625, 0.1. 0.05, a little hard to find the correct `s` value. Thank you.

I changed s = 0.0625, that is errors
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 2 (input tensor's size at dimension 2), but got split_sizes=[0, 0, 1]

**Comment by NguyenDangBinh** [comment]
Dear @jeya-maria-jose ,
Can you increase the size of image in dataset? Example: imgsize = 512, but not meet "Out of memory".
Thank you so much.
