### ISSUE TITLE
The question of the gated axial attention formula

### ISSUE THREAD

**Issue by wang-yu-xuan** [jeya-maria-jose/Medical-Transformer#18]
Excuse me, for the gated axial-attention formula, I can understant the setting of the gating parameters in the three positions of Gqr, Gkr and Gr, but why do you add the gating parameters on v, which has no position information.
Thank you!

**Comment by charleneolive** [comment]
Hello @jeya-maria-jose and @wang-yu-xuan , from what I understood from the code, the gated parameters Gq, Gk, Gv1 and Gv2 is just self.f_qr, self.f_kr, self.f_sve and self.f_sv on the code is it? They appear to be nn.Parameters with value of 0.1 and requires_grad = False. Does it mean that these parameters are not updated during training? Why then does Section 3.2 call them learnable parameters? How did you decide on the value of 0.1?

**Comment by jeya-maria-jose** [comment]
Hi @charleneolive , the gate parameters are not updated for the initial epochs to give an early start to the other parameters. From experiments, we found this configuration to work better. Later the requires_grad is set as True from 10th epoch.  https://github.com/jeya-maria-jose/Medical-Transformer/blob/10fb5a705d41d4fb88575dc4c3ff78abfe415153/train.py#L169

**Comment by charleneolive** [comment]
> Hi @charleneolive , the gate parameters are not updated for the initial epochs to give an early start to the other parameters. From experiments, we found this configuration to work better. Later the requires_grad is set as True from 10th epoch.
> 
> https://github.com/jeya-maria-jose/Medical-Transformer/blob/10fb5a705d41d4fb88575dc4c3ff78abfe415153/train.py#L169

Makes sense, thank you!
