### ISSUE TITLE
the test result of MoNuSeg Dataset

### ISSUE THREAD

**Issue by smd1997** [jeya-maria-jose/Medical-Transformer#23]
Hello, thanks for your  work!
The IoU of MoNuSeg Dataset in your colab code is 0.8400399344308036, while the IoU is  66.17% in your paper. Could you please explain what causes this difference?

**Comment by TangdoudouAN** [comment]
Excuse me, how do you calculate the IoU? I can't find the code of this part, could you help me? Thanks.

**Comment by jeya-maria-jose** [comment]
Please check the .m file to calculate IoU. The colab code was not written by me. I will sort out the issue with the colab file soon.
