### ISSUE TITLE
Running Issue:train_dataset = ImageToImage2D(args.train_dataset, tf_val)

### ISSUE THREAD

**Issue by lsq117** [jeya-maria-jose/Medical-Transformer#24]
Is some bugs in train.py?
For example——parser.add_argument('--train_dataset', required=True, type=str) 
I think here should exist the path of dataset,and when i add the path,there occurs other errors, that i shows as belows:
usage: train.py [-h] [-j N] [--epochs N] [--start-epoch N] [-b N]
                [--learning_rate LR] [--momentum M] [--weight-decay W]
                --train_dataset TRAIN_DATASET [--val_dataset VAL_DATASET]
                [--save_freq SAVE_FREQ] [--modelname MODELNAME] [--cuda CUDA]
                [--aug AUG] [--load LOAD] [--save SAVE] [--direc DIREC]
                [--crop CROP] [--imgsize IMGSIZE] [--device DEVICE]
                [--gray GRAY]
train.py: error: the following arguments are required: --train_dataset
An exception has occurred, use %tb to see the full traceback.
i have tried my best to try to understand utils.py(class ImageToImage2D(Dataset)),and cannot find the reason of debugs
Could author or friends give me a hand? Thank you very much...

**Comment by charleneolive** [comment]
The code works fine for me. Did you make sure that the dataset folder organisation matches what is said in the instructions? It seems that you did not actually specify the train_dataset path.
