### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by leolin65** [jeya-maria-jose/Medical-Transformer#27]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-23-7603b76039ad> in <module>()
      4         I = np.array(Image.open('/content/test folder/labelcol/'+i))
      5         I=np.where(I>=127,1,0)
----> 6         L = np.array(Image.open('/content/test_results/'+i))
      7         L=np.where(L>=127,1,0)
      8         y_true,y_pred = I.flatten(),L.flatten()

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2841 
   2842     if filename:
-> 2843         fp = builtins.open(filename, "rb")
   2844         exclusive_fp = True
   2845 

FileNotFoundError: [Errno 2] No such file or directory: '/content/test_results/0004.png'

**Comment by jeya-maria-jose** [comment]
This is an error exclusive to your file storage scheme. Try seeing if the directory path is right.
