### ISSUE TITLE
Is Gated Attention layer only used in the global branch?

### ISSUE THREAD

**Issue by cao13jf** [jeya-maria-jose/Medical-Transformer#29]
Hi, Jose. This work attracts me a lot and I attempt to test it on another dataset. While revising the source code, I found the *gated* axial attention layer seems to be only used in the global branch ([link](https://github.com/jeya-maria-jose/Medical-Transformer/blob/8a5a95b4d5cd66cc4043c7e6783f9eb71f173520/lib/models/axialnet.py#L539)). The local branch keeps using the axial attention module ([link](https://github.com/jeya-maria-jose/Medical-Transformer/blob/8a5a95b4d5cd66cc4043c7e6783f9eb71f173520/lib/models/axialnet.py#L572)).  Because this may be not referred in the paper, I just want to check whether I ignore something here. Thanks in advance.

**Comment by jeya-maria-jose** [comment]
Hi, Thank you for your interest in our work. Yes, whatever you have mentioned is right. It has been explained in section 3.2.

**Comment by cao13jf** [comment]
Get it. Thanks for your quick reply.
