### ISSUE TITLE
loss is nan

### ISSUE THREAD

**Issue by 775397252** [jeya-maria-jose/Medical-Transformer#3]
hello, i use GLAS resize dataset, but whith i run train.py, the loss is nan.
![image](https://user-images.githubusercontent.com/7972945/111311341-124bae00-8699-11eb-9737-b7412437c085.png)
my env is windows 10, and:
![image](https://user-images.githubusercontent.com/7972945/111311613-635ba200-8699-11eb-9298-ab34ffe6a71c.png)

**Comment by 775397252** [comment]
is the MedT model have not finish?

**Comment by jeya-maria-jose** [comment]
Hi, 

I just tried it again , it is working at my end. 

![Screenshot from 2021-03-16 11-55-34](https://user-images.githubusercontent.com/28985378/111339972-93ca1e80-864e-11eb-8714-7207d6f94e22.png)

These are the versions of the packages in my environment, maybe try downgrading torch to 1.4 from 1.8. Please use the requirements.txt to setup the exact environment.

![Screenshot from 2021-03-16 11-57-39](https://user-images.githubusercontent.com/28985378/111340222-d3910600-864e-11eb-8d67-7e2913fa5786.png)

**Comment by 775397252** [comment]
i use rtx3060, maybe i can not install torch1.4

**Comment by 775397252** [comment]
ok,when i delete a image ,it is fine.maybe the number of image should be Multiple of 4.
after train epoch for 400,i find it that  the effect is not very good.

**Comment by jeya-maria-jose** [comment]
Hi,
Can you please elaborate ?

**Comment by 775397252** [comment]
![image](https://user-images.githubusercontent.com/7972945/111570131-171a7a00-87df-11eb-98ff-c978494fb997.png)

The third picture is my training model,after train epoch for 600,i find it that the effect is not very good.like this.

if the train image not be Multiple of batch_size .maybe as follow:

![image](https://user-images.githubusercontent.com/7972945/111570268-652f7d80-87df-11eb-91be-997f74410b1b.png)

> If I have anyproblem, please point it out in time. Thank you for your work

**Comment by jeya-maria-jose** [comment]
Looks like the training breaks mid-way at your end. The batch size used for the experiment was 4. Will investigate with different batch sizes to check if that is a problem and get back.

**Comment by walynlee** [comment]
Hello, I had a similar problem in training.Can someone know?When the batch size is 4 and epoch is 400,I train these model and found it is not like as what the paper said.And I don't know how to solve this problem.

**Comment by jeya-maria-jose** [comment]
Hi @walynlee ,

I think 02.png is you have visualized here is different from what is in the dataset, I think the predictions are for a different input. Below is the input, prediction and GT respectively. 
![Screenshot from 2021-03-18 14-17-13](https://user-images.githubusercontent.com/28985378/111676922-0bd24900-87f5-11eb-96d8-814b608afe09.png)

Also, I will update the exact number of epochs and batch size that gives the best performance for each dataset in the next commit.
