### ISSUE TITLE
questions about imgsize and crop

### ISSUE THREAD

**Issue by ssli23** [jeya-maria-jose/Medical-Transformer#35]
When the ‘modelname’ is set to "logo", should the size of the parameter ‘crop’ be set to a quarter of ‘imgsize’? When I set ‘imgsize’ to 512 and ‘crop’ to 128 like this, the following error occurred: 
RuntimeError: einsum() operands do not broadcast with remapped shapes [original->remapped]: [64, 8, 1, 64]->[64, 8, 64, 1, 1] [1, 256, 256]->[1, 1, 256, 256, 1]
looking forward to your reply!

**Comment by jeya-maria-jose** [comment]
The crop argument is for cropping the input to patches of 128 (as input to global branch). It has nothing to do with the patches for the local branch.
