### ISSUE TITLE
The utils_gray.py for ImageToImage2D function

### ISSUE THREAD

**Issue by QiaoSiBo** [jeya-maria-jose/Medical-Transformer#36]
I have a question about a code for masks in ImageToImage2D function, which are as follows:

class ImageToImage2D(Dataset):
       ...
        mask[mask<127] = 0
        mask[mask>=127] = 1
      ...

Sorry, I don't understand why to do this process to the mask.  I will be very thanked for it if you can help me to work out.

**Comment by jeya-maria-jose** [comment]
It just converts the pixels of the mask from [0,255] to [0,1].

**Comment by QiaoSiBo** [comment]
Thank you very much. I get it now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeya-maria-jose/Medical-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeya-maria-jose/Medical-Transformer] The utils_gray.py for ImageToImage2D function (#36)





 
It just converts the pixels of the mask from [0,255] to [0,1].
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
