### ISSUE TITLE
Have problem in the MoNuSegTrainingData?

### ISSUE THREAD

**Issue by tphankr** [jeya-maria-jose/Medical-Transformer#37]
I could not see the label in the Annotations folder. In this folder has only .xml file. Please help me have labels in order train. Thank you.
![image](https://user-images.githubusercontent.com/37217354/129376464-6800895b-0ac5-4d08-a767-33ef831584bf.png)

![image](https://user-images.githubusercontent.com/37217354/129376776-0acd646a-c599-4077-9b5a-59355672dd46.png)
Thank you.

**Comment by jeya-maria-jose** [comment]
You will have a matlab script in that folder to convert these .xml files to .tiff files.

**Comment by tphankr** [comment]
Thank you @jeya-maria-jose ,
Please help me, How do I run the "he_to_binary_mask_final.m" file ( this file is the convert file as you comment). 
![image](https://user-images.githubusercontent.com/37217354/129822976-d96f9ed2-185f-4903-9985-2a2f98ad5375.png)
The link to dataset is ./MoNuSegTraningData/Annotations

Thank you @jeya-maria-jose very much.

**Comment by jeya-maria-jose** [comment]
You should send input the directory containing .xml files as the input argument to the function.
