### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by 1322574159** [jeya-maria-jose/Medical-Transformer#38]

**Comment by 1322574159** [comment]
Can you put the datasets in the web disk and give a link

**Comment by 123xu223** [comment]
can you provide the  processed  datasets for me about the  MedT ?Thank you very much

**Comment by YUCOCOCS** [comment]
can you provide the processed datasets for me about the MedT ?Thank you very much

**Comment by kuku609** [comment]
can you provide the processed datasets for me about the MedT ?Thank you very much
