### ISSUE TITLE
Image size when training with Glas dataset

### ISSUE THREAD

**Issue by weiaicunzai** [jeya-maria-jose/Medical-Transformer#4]
Thanks for your great work, and I need some help on training Glas datset. Could you please tell me the image size you used for training Glas dataset?Cause the images in Glas dataset tend to have different  size, 775 x 522, 589 x 453 and 567 x 430, which need to be converted to the same shape before sending to the network,  and 128x128 is just to small for training Glas dataset,. Thanks.

**Comment by jeya-maria-jose** [comment]
Hi,

Thanks for your comment. We  resized all the images to 128x128 for our experiment as well as baseline comparisons. I agree that training on a higher resolution might be more helpful and result in a better performance. As we just focused on making the case for MedT, we just followed a standard resolution for all the experiments. We can definitely analyse doing patch wise training for MedT as well as other baselines for GlaS in the future to further push the performance.

**Comment by weiaicunzai** [comment]
> Hi,
> 
> Thanks for your comment. We resized all the images to 128x128 for our experiment as well as baseline comparisons. I agree that training on a higher resolution might be more helpful and result in a better performance. As we just focused on making the case for MedT, we just followed a standard resolution for all the experiments. We can definitely analyse doing patch wise training for MedT as well as other baselines for GlaS in the future to further push the performance.

Thanks for your replay, just want to make sure, during the evaluation phase, you  resize the output prediction of network from 128 * 128 to the original image size?

**Comment by jeya-maria-jose** [comment]
During evaluation, we resize the ground truth also to 128*128 resolution to match the predictions.
