### ISSUE TITLE
Hello, I reported an error after training. The loss value has always been 0. How can I solve it?

### ISSUE THREAD

**Issue by 123xu223** [jeya-maria-jose/Medical-Transformer#48]
libpng warning: iCCP: known incorrect sRGB profile
epoch [0/400], loss:0.2294
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
epoch [1/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [2/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [3/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [4/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [5/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [6/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [7/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [8/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [9/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [10/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
epoch [11/400], loss:0.0000
libpng warning: iCCP: known incorrect sRGB profile
epoch [12/400], loss:0.0000

**Comment by 123xu223** [comment]
训练时候我的loss值一直是0，请问怎么办呢？

**Comment by jeya-maria-jose** [comment]
This is some problem with the way you are storing your dataset. Please double check about the libpng warning.
