### ISSUE TITLE
test

### ISSUE THREAD

**Issue by He9702** [jeya-maria-jose/Medical-Transformer#5]
This is my testing command: python test.py --loaddirec "./medtfinal_model.pth" --val_dataset "./val/" --batch_size 1 --modelname "gatedaxialunet" --imgsize 128 --gray "no"

But what makes me strange is that it seems to have some problems, can you help me solve it?
![图片](https://user-images.githubusercontent.com/71333170/111857942-0cdbb580-8970-11eb-910c-39f7e3a1a1f3.png)

**Comment by jeya-maria-jose** [comment]
Hi, Please make sure the .pth file you are loading is valid. If you are using multiple GPUs, please nn.DataParallel to the code.

**Comment by He9702** [comment]
The advice given to my problem is very helpful to me, I already know what my problem is, thank you very much


| |
贺琪琪
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/23/2021 22:58，Jeya Maria ***@***.***> wrote：

Hi, Please make sure the .pth file you are loading is valid. If you are using multiple GPUs, please nn.DataParallel to the code.
