### ISSUE TITLE
question about the axial attention code

### ISSUE THREAD

**Issue by loriphy** [jeya-maria-jose/Medical-Transformer#64]
Thanks for your great work, I have learned a lot from it.
But there is one question when I read the code, hoping to get solved.
1. axialnet.py, Line158
         qr = torch.einsum('bgci,cij->bgij', q, q_embedding)
        kr = torch.einsum('bgci,cij->bgij', k, k_embedding).transpose(2, 3)
        qk = torch.einsum('bgci, bgcj->bgij', q, k)
    Why kr need to be transposed? It doesn't seem to be transposed in the formula.

**Comment by jeya-maria-jose** [comment]
Thank you for your interest in the work.

 It is transposed to perform tensor multiplication between q and k along the right index.
