### ISSUE TITLE
Gated Mechanism

### ISSUE THREAD

**Issue by QiaoSiBo** [jeya-maria-jose/Medical-Transformer#70]
In the Gated parameters, why are they all requires_grad=False?
        # Priority on encoding

        ## Initial values 

        self.f_qr = nn.Parameter(torch.tensor(0.1),  requires_grad=False)
        self.f_kr = nn.Parameter(torch.tensor(0.1),  requires_grad=False)
        self.f_sve = nn.Parameter(torch.tensor(0.1),  requires_grad=False)
        self.f_sv = nn.Parameter(torch.tensor(1.0),  requires_grad=False)

**Comment by jeya-maria-jose** [comment]
They are not trained for the first few epochs they are made requires_grad = True after few initial epochs.

**Comment by QiaoSiBo** [comment]
> They are not trained for the first few epochs they are made requires_grad = True after few initial epochs.
Thanks a lot.
