### ISSUE TITLE
 Problem on training Glas dataset

### ISSUE THREAD

**Issue by wenwen-gu** [jeya-maria-jose/Medical-Transformer#8]
Thanks for your nice work . Since I just got in touch with this research direction, I meet some problems on training Glas dataset. Hope for your help!
I don’t know what went wrong, which made it impossible to train normally.
![图片](https://user-images.githubusercontent.com/76939082/112951792-55645180-916e-11eb-85b6-5597ec71299a.png)
my env is Ubuntu18.04, All dependencies are consistent with your suggestions.
![图片](https://user-images.githubusercontent.com/76939082/112951853-6614c780-916e-11eb-91d7-71f440b13960.png)
  Glas dataset has been prepared in the following format           
![图片](https://user-images.githubusercontent.com/76939082/112951896-7167f300-916e-11eb-8734-e861b1e21a1e.png)
![图片](https://user-images.githubusercontent.com/76939082/112952007-93fa0c00-916e-11eb-9480-2f1f9aa814a0.png)

**Comment by sstary** [comment]
Hello， I met this problem too, could you help me?

If you have time, my wechat is 13277987978, I really need some advice.
