### ISSUE TITLE
The type of "args.train_dataset" and "args.val_dataset" in test.py is "None"

### ISSUE THREAD

**Issue by Ytwo2** [jeya-maria-jose/Medical-Transformer#84]
When I tested it I entered the following code：
`python test.py --loaddirec "./my_model.pth" --val_dataset "./img/test/" --direc './test_result/' --batch_size 1 --modelname "gatedaxialunet" --imgsize 128 --gray "no"`

And I got：
`Traceback (most recent call last):
File "test.py", line 84, in <module>
    train_dataset = ImageToImage2D(args.train_dataset, tf_val)
File "/home/Medical-Transformer/utils.py", line 130, in __init__
    self.input_path = os.path.join(dataset_path, 'img')
File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

So I printed the type of "tf_val" and "args.train_dataset" and the result is as follows：
`val:<class 'utils.JointTransform2D'>
train: None` 

Is it necessary to solve this problem by adding default to the front parameter design?
change
`parser.add_argument('--train_dataset', type=str)
parser.add_argument('--val_dataset', type=str)`
to
`parser.add_argument('--train_dataset', default='./path1/', type=str)
parser.add_argument('--val_dataset', default='./path2/', type=str)`

If so, what path do I need to put in default? Is it 'img' or 'label' or the result of training?

**Comment by diogocid** [comment]
I have the same problem here, how you resolve the problem?

**Comment by algwang** [comment]
> 当我测试它时，我输入了以下代码： `python test.py --loaddirec "./my_model.pth" --val_dataset "./img/test/" --direc './test_result/' --batch_size 1 --modelname "gatedaxialunet" --imgsize 128 --gray "no"`
> 
> 我得到了： `Traceback (most recent call last): File "test.py", line 84, in <module> train_dataset = ImageToImage2D(args.train_dataset, tf_val) File "/home/Medical-Transformer/utils.py", line 130, in __init__ self.input_path = os.path.join(dataset_path, 'img') File "/usr/lib/python3.8/posixpath.py", line 76, in join a = os.fspath(a) TypeError: expected str, bytes or os.PathLike object, not NoneType`
> 
> 所以我打印了 “tf_val” 和 “args.train_dataset” 的类型，结果如下： `val:<class 'utils.JointTransform2D'> train: None`
> 
> 是否有必要通过在 front 参数 design 中添加 default 来解决这个问题？更改为 `parser.add_argument('--train_dataset', type=str) parser.add_argument('--val_dataset', type=str)` `parser.add_argument('--train_dataset', default='./path1/', type=str) parser.add_argument('--val_dataset', default='./path2/', type=str)`
> 
> 如果是这样，我需要在 default 中输入哪个路径？是 'img' 还是 'label' 还是训练的结果？

您好，请问是怎么解决这个问题的，希望可以回答一下，谢谢

**Comment by algwang** [comment]
> I have the same problem here, how you resolve the problem?

Hi, how did you solve this problem?

**Comment by diogocid** [comment]
Yes, but now I'm not sure what I did. Maybe the image path was incorrect.

**Comment by algwang** [comment]
> Yes, but now I'm not sure what I did. Maybe the image path was incorrect.

Thank you for your patience. How did you print the log to check the results of F1 and Iou when you tested it? Could you provide your code for reference? I will be very grateful for your help. Thank you.

**Comment by diogocid** [comment]
In my case I choose to create a new function to calculate IoU.
I show you the code but maybe not very easy to understand
last lines in test.py

`
predictions = []
ground_truths = []
iou_classes = [[] for _ in range(args.num_classes)]
precision_classes = [[] for _ in range(args.num_classes)]
recall_classes = [[] for _ in range(args.num_classes)]

for batch_idx, (X_batch, y_batch, *rest) in enumerate(valloader):
    if isinstance(rest[0][0], str):
        image_filename = rest[0][0]
    else:
        image_filename = '%s.png' % str(batch_idx + 1).zfill(3)

    X_batch = Variable(X_batch.to(device='cuda'))
    y_batch = Variable(y_batch.to(device='cuda'))

    y_out = model(X_batch)
    predicted_masks = torch.argmax(y_out, dim=1).detach().cpu().numpy()
    yval = y_batch.detach().cpu().numpy()
    ground_truths.append(yval)
    predictions.append(predicted_masks)
    
    fulldir = os.path.join(direc, "predictions")
    os.makedirs(fulldir, exist_ok=True)
    predicted_masks = predicted_masks * 85  # Escalar para visualização
    # Save predictions
    cv2.imwrite(os.path.join(fulldir, image_filename), predicted_masks[0])
    
# Convert to numpy arrays
predictions = np.array(predictions).reshape(-1, *predicted_masks.shape[1:])
ground_truths = np.array(ground_truths).reshape(-1, *predicted_masks.shape[1:])

# calculate metrics
iou, precision, recall = calculate_classwise_metrics(predictions, ground_truths, num_classes=args.num_classes)

# show metrics 
for cls in range(args.num_classes):
    print(f"Segmentação Test - Class {cls} - IoU: {iou[cls]:.4f}, Precision: {precision[cls]:.4f}, Recall: {recall[cls]:.4f}")
    iou_classes[cls].append(iou[cls])
    precision_classes[cls].append(precision[cls])
    recall_classes[cls].append(recall[cls])
`
