### ISSUE TITLE
About CUDA out of memory

### ISSUE THREAD

**Issue by louan1998** [jeya-maria-jose/Medical-Transformer#86]
这个模型跑起来到底要多少显存？我这里有两张40G的A100居然还爆显存

**Comment by nightrain-vampire** [comment]
Perhaps changing the scale of the image to a smaller size would help?

**Comment by louan1998** [comment]
> Perhaps changing the scale of the image to a smaller size would help?

yes! I change the training image size. The first time I use the 1000 * 1000 size picture, then I changed it to 256 * 256, and it worked!
