### ISSUE TITLE
Request for GLAS and MoNuSeG preprocessed datasets.

### ISSUE THREAD

**Issue by mustansarfiaz** [jeya-maria-jose/Medical-Transformer#89]
Hi,

The datasets downloaded from the links are not in the format you are using. Could you please provide the preprocessed GLAS and MoNuSeG datasets for your code? Or please provide the script so that I can prepare the dataset and train your model.

Regrads
Mustansar

**Comment by NadiaBadawi88** [comment]
hello Mustansar
did you get the data set?

**Comment by mustansarfiaz** [comment]
yes 
I got it.
Thank you.

**Comment by kuku609** [comment]
> yes I got it. Thank you.

Do you still have this dataset, if so can you send me a copy of the dataset, I can't find these datasets online anymore.
