### ISSUE TITLE
How to calculate IoU?

### ISSUE THREAD

**Issue by StevenAZy** [jeya-maria-jose/Medical-Transformer#9]
I run the test.py on validation dataset of MoNuSegData, which generate some prediction images. I used these prediction image and ground truth of validation dataset to calculate IoU, but i achieved the IoU that is not same as yours. I think that i have some misunderstanding about the way of calculating IoU, so i want to ask how to calculate IoU.

**Comment by jeya-maria-jose** [comment]
You can use the performancemetrics_monuseg.m code provided in the repo !
